import * as chartHandlers from "@/services/transaction/chart"
import { ResponsiveLayouts } from "@/types"
import { ChartId, ChartHandler } from "@/types/Transaction"

export const SUPPORTED_CHARTS = [
  "ProfitChart",
  "RealizedPnlChart",
  "TradeFundBase",
  "TradeSummary",
  "TradeLog",
  "TradePlan",
  "GoalProgress",
  "PortfolioAllocationChart"
] as const

// Chart handlers for each chart type
export const CHART_HANDLERS: Record<ChartId, ChartHandler> = {
  ProfitChart: chartHandlers.calculateProfitChart,
  RealizedPnlChart: chartHandlers.calculateRealizedPnlChart,
  TradeFundBase: chartHandlers.calculateTradeFundBase,
  TradeSummary: chartHandlers.calculateTradeSummary,
  TradeLog: chartHandlers.calculateTradeLog,
  TradePlan: chartHandlers.calculateTradePlan,
  GoalProgress: chartHandlers.calculateGoalProgress,
  PortfolioAllocationChart: chartHandlers.calculatePortfolioAllocationChart,
}

export const BREAKPOINTS = ["lg", "md", "sm", "xs", "xxs"] as const

// Default Layout => 6 items
export const DEFAULT_LAYOUTS = {
  lg: [
    {
      w: 5,
      h: 8,
      x: 0,
      y: 9,
      i: "0",
      minW: 3,
      minH: 8,
      moved: false,
      static: false,
      chartId: "ProfitChart",
    },
    {
      w: 4,
      h: 18,
      x: 9,
      y: 9,
      i: "1",
      minW: 4,
      minH: 12,
      moved: false,
      static: false,
      chartId: "TradePlan",
    },
    {
      w: 4,
      h: 8,
      x: 5,
      y: 9,
      i: "2",
      minW: 4,
      minH: 8,
      moved: false,
      static: false,
      chartId: "RealizedPnlChart",
    },
    {
      w: 8,
      h: 10,
      x: 5,
      y: 0,
      i: "3",
      minW: 7,
      minH: 8,
      moved: false,
      static: false,
      chartId: "TradeFundBase",
    },
    {
      w: 9,
      h: 10,
      x: 0,
      y: 17,
      i: "4",
      minW: 5,
      minH: 9,
      moved: false,
      static: false,
      chartId: "TradeLog",
    },
    {
      w: 5,
      h: 10,
      x: 0,
      y: 0,
      i: "5",
      minW: 5,
      minH: 6,
      moved: false,
      static: false,
      chartId: "TradeSummary",
    },
  ],
  md: [
    {
      w: 5,
      h: 8,
      x: 0,
      y: 9,
      i: "0",
      minW: 3,
      minH: 8,
      moved: false,
      static: false,
      chartId: "ProfitChart",
    },
    {
      w: 5,
      h: 16,
      x: 5,
      y: 9,
      i: "1",
      minW: 4,
      minH: 12,
      moved: false,
      static: false,
      chartId: "TradePlan",
    },
    {
      w: 5,
      h: 8,
      x: 0,
      y: 17,
      i: "2",
      minW: 4,
      minH: 8,
      moved: false,
      static: false,
      chartId: "RealizedPnlChart",
    },
    {
      w: 6,
      h: 10,
      x: 4,
      y: 0,
      i: "3",
      minW: 6,
      minH: 8,
      moved: false,
      static: false,
      chartId: "TradeFundBase",
    },
    {
      w: 10,
      h: 10,
      x: 0,
      y: 25,
      i: "4",
      minW: 5,
      minH: 9,
      moved: false,
      static: false,
      chartId: "TradeLog",
    },
    {
      w: 4,
      h: 10,
      x: 0,
      y: 0,
      i: "5",
      minW: 4,
      minH: 6,
      moved: false,
      static: false,
      chartId: "TradeSummary",
    },
  ],
  sm: [
    {
      w: 3,
      h: 8,
      x: 0,
      y: 16,
      i: "0",
      minW: 3,
      minH: 8,
      moved: false,
      static: false,
      chartId: "ProfitChart",
    },
    {
      w: 6,
      h: 12,
      x: 0,
      y: 24,
      i: "1",
      minW: 4,
      minH: 12,
      moved: false,
      static: false,
      chartId: "TradePlan",
    },
    {
      w: 3,
      h: 8,
      x: 3,
      y: 16,
      i: "2",
      minW: 3,
      minH: 8,
      moved: false,
      static: false,
      chartId: "RealizedPnlChart",
    },
    {
      w: 6,
      h: 10,
      x: 0,
      y: 0,
      i: "3",
      minW: 5,
      minH: 8,
      moved: false,
      static: false,
      chartId: "TradeFundBase",
    },
    {
      w: 6,
      h: 10,
      x: 0,
      y: 36,
      i: "4",
      minW: 5,
      minH: 9,
      moved: false,
      static: false,
      chartId: "TradeLog",
    },
    {
      w: 6,
      h: 9,
      x: 0,
      y: 7,
      i: "5",
      minW: 5,
      minH: 6,
      moved: false,
      static: false,
      chartId: "TradeSummary",
    },
  ],
  xs: [
    {
      w: 4,
      h: 8,
      x: 0,
      y: 25,
      i: "0",
      minW: 3,
      minH: 8,
      moved: false,
      static: false,
      chartId: "ProfitChart",
    },
    {
      w: 4,
      h: 12,
      x: 0,
      y: 33,
      i: "1",
      minW: 4,
      minH: 12,
      moved: false,
      static: false,
      chartId: "TradePlan",
    },
    {
      w: 4,
      h: 8,
      x: 0,
      y: 17,
      i: "2",
      minW: 4,
      minH: 8,
      moved: false,
      static: false,
      chartId: "RealizedPnlChart",
    },
    {
      w: 4,
      h: 8,
      x: 0,
      y: 0,
      i: "3",
      minW: 5,
      minH: 7,
      moved: false,
      static: false,
      chartId: "TradeFundBase",
    },
    {
      w: 4,
      h: 10,
      x: 0,
      y: 45,
      i: "4",
      minW: 5,
      minH: 9,
      moved: false,
      static: false,
      chartId: "TradeLog",
    },
    {
      w: 4,
      h: 9,
      x: 0,
      y: 8,
      i: "5",
      minW: 5,
      minH: 6,
      moved: false,
      static: false,
      chartId: "TradeSummary",
    },
  ],
  xxs: [
    {
      w: 2,
      h: 8,
      x: 0,
      y: 29,
      i: "0",
      minW: 3,
      minH: 8,
      moved: false,
      static: false,
      chartId: "ProfitChart",
    },
    {
      w: 2,
      h: 12,
      x: 0,
      y: 17,
      i: "1",
      minW: 4,
      minH: 12,
      moved: false,
      static: false,
      chartId: "TradePlan",
    },
    {
      w: 2,
      h: 8,
      x: 0,
      y: 37,
      i: "2",
      minW: 4,
      minH: 8,
      moved: false,
      static: false,
      chartId: "RealizedPnlChart",
    },
    {
      w: 2,
      h: 8,
      x: 0,
      y: 0,
      i: "3",
      minW: 5,
      minH: 7,
      moved: false,
      static: false,
      chartId: "TradeFundBase",
    },
    {
      w: 2,
      h: 10,
      x: 0,
      y: 45,
      i: "4",
      minW: 5,
      minH: 9,
      moved: false,
      static: false,
      chartId: "TradeLog",
    },
    {
      w: 2,
      h: 9,
      x: 0,
      y: 8,
      i: "5",
      minW: 5,
      minH: 6,
      moved: false,
      static: false,
      chartId: "TradeSummary",
    },
  ],
} as const as ResponsiveLayouts

// Toolboxt
export const DEFAULT_TOOLBOX = {
  xxs: [
    {
      w: 5,
      h: 6,
      x: 0,
      y: 0,
      i: "6",
      minW: 4,
      minH: 5,
      moved: false,
      static: false,
      chartId: "GoalProgress",
    },
  ],
  xs: [
    {
      w: 5,
      h: 6,
      x: 0,
      y: 0,
      i: "6",
      minW: 4,
      minH: 5,
      moved: false,
      static: false,
      chartId: "GoalProgress",
    },
  ],
  sm: [
    {
      w: 6,
      h: 6,
      x: 0,
      y: 0,
      i: "6",
      minW: 4,
      minH: 5,
      moved: false,
      static: false,
      chartId: "GoalProgress",
    },
  ],
  md: [
    {
      w: 4,
      h: 6,
      x: 0,
      y: 0,
      i: "6",
      minW: 4,
      minH: 5,
      moved: false,
      static: false,
      chartId: "GoalProgress",
    },
  ],
  lg: [
    {
      w: 5,
      h: 6,
      x: 0,
      y: 0,
      i: "6",
      minW: 4,
      minH: 5,
      moved: false,
      static: false,
      chartId: "GoalProgress",
    },
  ],
} as const as ResponsiveLayouts
